// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentAccessPortal.Model;

namespace PaymentAccessPortal.Migrations
{
    [DbContext(typeof(PaymentAccessPortalContext))]
    partial class PaymentAccessPortalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaymentAccessPortal.Model.PaymentCardDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<string>("CardHolder");

                    b.Property<string>("CreditCardNumber");

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<string>("PaymentState");

                    b.Property<string>("SecurityCode");

                    b.HasKey("Id");

                    b.ToTable("PaymentCardDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
